### ISSUE TITLE
Provide Pytorch notebooks

### ISSUE THREAD

**Issue by impredicative** [DeepLearningSaeid/New-Type-of-Deep-Learning#1]
Thanks for the notebooks using Keras which are nice. Is it also possible to add a set of notebooks that use Pytorch?

**Comment by DeepLearningSaeid** [comment]
Hi, Thank you For your comments.
Yes. I am trying to develop a library for that.
I have developed a custom Layer in Keras which you can use this model in just one line.

**Comment by impredicative** [comment]
A one-liner for Pytorch would also be appreciated. As we know, both Keras and Pytorch are heavily used these days.
