### ISSUE TITLE
can you provide the evalutation comparsions among other methods?

### ISSUE THREAD

**Issue by novioleo** [DeepLearningSaeid/New-Type-of-Deep-Learning#2]

**Comment by DeepLearningSaeid** [comment]
Hi, 
Thank you for your response. in this link 

  https://github.com/DeepLearningSaeid/New-Type-of-Deep-Learning/blob/master/SWAG_EXP_1.ipynb

and 

 https://github.com/DeepLearningSaeid/New-Type-of-Deep-Learning/blob/master/SWAG_EXP_2.ipynb

we ran our method against 5 different traditional deep learning methods. and here we use 7 public datasets which are so popular.
but there are million different architectures we can run against this algorithm.

**Comment by novioleo** [comment]
thks for your reply.
